### PR TITLE
Always use EventFormat.DIALOGUE for template

### PR DESCRIPTION
**Pull request by xIceArcher**

### CODE REVIEW

**Comment by ahuei123456** [comment]
I think there was one test that needs to be updated for this too, run `pytest` and see which one fails.

**Comment by xIceArcher** [comment]
Oops, updated

**Comment by ahuei123456** [comment]
It would probably make more sense to update the test to always check that it's pyass.EventFormat.DIALOGUE rather than changing the inputs.

**Comment by xIceArcher** [comment]
> It would probably make more sense to update the test to always check that it's pyass.EventFormat.DIALOGUE rather than changing the inputs.

But isn't that what the test is already doing?

Unless I'm mistaken, the variable `format` is the expected format since line 102 has `assert event.format == format`

**Comment by ahuei123456** [comment]
Yeah, you're right. I mixed it up with the other flags getting passed in.

**Pull request merged**
